-- Rayner Mendez
-- 23253396
-- https://github.com/RaynerMDZ
-- https://www.linkedin.com/in/raynermendez/
CREATE DATABASE caribbean_cuisine_restaurant;

USE caribbean_cuisine_restaurant;

ALTER SESSION
SET
    NLS_DATE_FORMAT = 'MM/DD/RRRR';

-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-21 11:05:29 EST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
-- predefined type, no DDL - XMLTYPE
CREATE TABLE address (
    address_id INTEGER NOT NULL,
    address_line_1 VARCHAR2(150 BYTE) NOT NULL,
    address_line_2 VARCHAR2(150 BYTE),
    city VARCHAR2(150 BYTE) NOT NULL,
    state_code CHAR(2 BYTE) NOT NULL,
    zipcode VARCHAR2(10 BYTE) NOT NULL,
    country VARCHAR2(100 BYTE) NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE
);

ALTER TABLE
    address
ADD
    CONSTRAINT address_pk PRIMARY KEY (address_id);

CREATE TABLE credit_card (
    credit_card_number VARCHAR2(16 BYTE) NOT NULL,
    owner_name VARCHAR2(300 BYTE) NOT NULL,
    merchant_name VARCHAR2(50 BYTE) NOT NULL,
    exp_date DATE NOT NULL,
    credit_card_limit NUMBER(8, 2) NOT NULL,
    credit_card_balance NUMBER(8, 2) NOT NULL,
    address_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX credit_card__idx ON credit_card (address_id ASC);

ALTER TABLE
    credit_card
ADD
    CONSTRAINT credit_card_pk PRIMARY KEY (credit_card_number);

CREATE TABLE customer (
    customer_id INTEGER NOT NULL,
    first_name VARCHAR2(200 BYTE) NOT NULL,
    last_name VARCHAR2(200 BYTE) NOT NULL,
    cellphone VARCHAR2(15 BYTE),
    email VARCHAR2(255),
    creation_date DATE NOT NULL,
    modified_date DATE
);

ALTER TABLE
    customer
ADD
    CONSTRAINT customer_pk PRIMARY KEY (customer_id);

CREATE TABLE delivery (
    delivery_id INTEGER NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE,
    address_id INTEGER NOT NULL,
    orders_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    employee_id SMALLINT NOT NULL
);

CREATE UNIQUE INDEX delivery__idx ON delivery (address_id ASC);

CREATE UNIQUE INDEX delivery__idxv4 ON delivery (orders_id ASC);

CREATE UNIQUE INDEX delivery__idxv1 ON delivery (customer_id ASC);

CREATE UNIQUE INDEX delivery__idxv2 ON delivery (employee_id ASC);

ALTER TABLE
    delivery
ADD
    CONSTRAINT delivery_pk PRIMARY KEY (delivery_id);

CREATE TABLE discount (
    discount_code VARCHAR2(10 BYTE) NOT NULL,
    percentage NUMBER(5, 2) NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE NOT NULL,
    active CHAR(1) NOT NULL
);

ALTER TABLE
    discount
ADD
    CONSTRAINT discount_pk PRIMARY KEY (discount_code);

CREATE TABLE employee (
    employee_id SMALLINT NOT NULL,
    first_name VARCHAR2(150 BYTE) NOT NULL,
    last_name VARCHAR2(150 BYTE) NOT NULL,
    date_of_birth DATE NOT NULL,
    cellphone VARCHAR2(20) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    position VARCHAR2(150 BYTE) NOT NULL,
    active CHAR(1) NOT NULL,
    salary NUMBER(8, 2) NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE,
    address_id INTEGER NOT NULL,
    location_id SMALLINT NOT NULL
);

CREATE UNIQUE INDEX employee__idx ON employee (address_id ASC);

ALTER TABLE
    employee
ADD
    CONSTRAINT employee_pk PRIMARY KEY (employee_id);

CREATE TABLE inventory (
    item_id INTEGER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    quantity SMALLINT NOT NULL,
    category VARCHAR2(50 BYTE) NOT NULL,
    exp_date DATE NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE
);

ALTER TABLE
    inventory
ADD
    CONSTRAINT inventory_pk PRIMARY KEY (item_id);

CREATE TABLE location (
    location_id SMALLINT NOT NULL,
    address_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX location__idx ON location (address_id ASC);

ALTER TABLE
    location
ADD
    CONSTRAINT location_pk PRIMARY KEY (location_id);

CREATE TABLE order_item (
    order_item_id SMALLINT NOT NULL,
    orders_id INTEGER NOT NULL,
    inventory_item_id INTEGER NOT NULL,
    recipe_id SMALLINT NOT NULL
);

ALTER TABLE
    order_item
ADD
    CONSTRAINT order_item_pk PRIMARY KEY (order_item_id);

CREATE TABLE orders (
    order_id INTEGER NOT NULL,
    order_price NUMBER(8, 2) NOT NULL,
    tax NUMBER(8, 2) NOT NULL,
    total_amount NUMBER(8, 2) NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE,
    customer_id INTEGER NOT NULL,
    credit_card_number VARCHAR2(16 BYTE) NOT NULL,
    discount_code VARCHAR2(10 BYTE) NOT NULL
);

ALTER TABLE
    orders
ADD
    CONSTRAINT orders_pk PRIMARY KEY (order_id);

CREATE TABLE recipe (
    recipe_id SMALLINT NOT NULL,
    recipe_name VARCHAR2(150 BYTE) NOT NULL,
    calories SMALLINT NOT NULL,
    is_vegan CHAR(1) NOT NULL,
    is_available CHAR(1) NOT NULL,
    creation_date DATE NOT NULL,
    modified_date DATE,
    employee_id SMALLINT NOT NULL,
    description VARCHAR2(500) NOT NULL,
    category VARCHAR2(100 BYTE) NOT NULL,
    price NUMBER(8, 2) NOT NULL
);

ALTER TABLE
    recipe
ADD
    CONSTRAINT recipe_pk PRIMARY KEY (recipe_id);

ALTER TABLE
    credit_card
ADD
    CONSTRAINT credit_card_address_fk FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE
    delivery
ADD
    CONSTRAINT delivery_address_fk FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE
    delivery
ADD
    CONSTRAINT delivery_customer_fk FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE
    delivery
ADD
    CONSTRAINT delivery_employee_fk FOREIGN KEY (employee_id) REFERENCES employee (employee_id);

ALTER TABLE
    delivery
ADD
    CONSTRAINT delivery_orders_fk FOREIGN KEY (orders_id) REFERENCES orders (order_id);

ALTER TABLE
    employee
ADD
    CONSTRAINT employee_address_fk FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE
    employee
ADD
    CONSTRAINT employee_location_fk FOREIGN KEY (location_id) REFERENCES location (location_id);

ALTER TABLE
    location
ADD
    CONSTRAINT location_address_fk FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE
    order_item
ADD
    CONSTRAINT order_item_inventory_fk FOREIGN KEY (inventory_item_id) REFERENCES inventory (item_id);

ALTER TABLE
    order_item
ADD
    CONSTRAINT order_item_orders_fk FOREIGN KEY (orders_id) REFERENCES orders (order_id);

ALTER TABLE
    order_item
ADD
    CONSTRAINT order_item_recipe_fk FOREIGN KEY (recipe_id) REFERENCES recipe (recipe_id);

ALTER TABLE
    orders
ADD
    CONSTRAINT orders_credit_card_fk FOREIGN KEY (credit_card_number) REFERENCES credit_card (credit_card_number);

ALTER TABLE
    orders
ADD
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE
    orders
ADD
    CONSTRAINT orders_discount_fk FOREIGN KEY (discount_code) REFERENCES discount (discount_code);

ALTER TABLE
    recipe
ADD
    CONSTRAINT recipe_employee_fk FOREIGN KEY (employee_id) REFERENCES employee (employee_id);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             7
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0 
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0